name: React Demo Test

# on: [push, workflow_dispatch]
on:
  push:
    branches:
      - main
      - dev
  workflow_dispatch:

env:
  DB_NAME: demo-db

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Access env var
        run: |
          echo "DB Name: ${{env.DB_NAME}}"
      - name: Code checkout
        uses: actions/checkout@v3           # By default, the current repo is checked out via ${{ github.repository}}
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Cache dependencies            # Caching helps other jobs to reuse the cached dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          # Key is used to retrieve the cache in the future and also to indicate if the cache should be discarded bcos
          # some dependency changed. 
          key: deps-node-modules-${{hashFiles('**/package-lock.json')}}
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test

  build:
    needs: test
    runs-on: ubuntu-latest
    outputs:
      script-file: ${{steps.publish.outputs.filename}}
    steps:
      - name: Code checkout
        uses: actions/checkout@v3
      - name: Cache dependencies            # Caching helps other jobs to reuse the cached dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: deps-node-modules-${{hashFiles('**/package-lock.json')}}
      - name: Install dependencies
        run: npm ci
      - name: Build project
        run: npm run build
      - name: Publish JS filename
        id: publish
        run: find dist/assets/*.js -type f -execdir echo 'filename={}' >> $GITHUB_OUTPUT ';'
      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          name: build-artifacts
          path: dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v8
        with:
          name: build-artifacts
      - name: Output contents
        run: ls
      - name: Output filename
        run: echo "${{needs.build.outputs.script-file}}"
      - name: Deploy
        run: echo "Deploying..."
