name: Workflow 01

on: workflow_dispatch

jobs:
  job-01:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        run: echo "Repository checkout"
      - name: Build
        run: echo "Running build"
